services:
  cache:
    image: redis
    container_name: redis
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start_interval: 5s
      # start_period: 30s

  directus:
    image: directus/directus
    container_name: directus
    cap_add:
      - NET_RAW
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      cache:
        condition: service_healthy
    environment:
      SECRET: "${DIRECTUS_SECRET}"
      DB_CLIENT: "${DB_CLIENT:-pg}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_SSL: "${DB_SSL:-true}"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

      # PUBLIC_URL: "http://localhost:8055"
      PUBLIC_URL: "${PUBLIC_URL:-https://cms.clubaviazionepopolare.org}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
