"""Read-only inventory contracts and source clients."""

from .canonical import (
    CanonicalizationError,
    canonical_json,
    canonical_json_bytes,
    canonical_sha256,
    canonicalize,
    freeze_json,
    normalize_json,
    sha256_bytes,
    sha256_hex,
    thaw_json,
)
from .errors import InventoryContractError, PaginationContractError
from .jsonl import read_manifest_jsonl, render_manifest_jsonl
from .models import InventoryScope, IssueSeverity
from .pagination import (
    InventoryPage,
    PageMeta,
    PageMetadata,
    PageResult,
    PaginationAccumulator,
    PaginationError,
    merge_complete_pages,
    wordpress_page_meta,
)
from .models import InventoryIssue, InventoryManifest, ManifestRecord
from .reconciliation import (
    HistoricalMappingEvidence,
    ReconciliationEvidence,
    ReconciliationEvidenceKind,
    ReconciliationReport,
    ReconciliationResult,
    ReconciliationState,
    historical_mappings_from_parser_yaml,
    reconcile_manifest_files,
    reconcile_manifests,
    reconcile_record,
)

__all__ = [
    "CanonicalizationError",
    "HistoricalMappingEvidence",
    "InventoryContractError",
    "InventoryIssue",
    "InventoryManifest",
    "InventoryPage",
    "InventoryScope",
    "ManifestRecord",
    "PageMeta",
    "PageMetadata",
    "PageResult",
    "PaginationAccumulator",
    "PaginationContractError",
    "PaginationError",
    "ReconciliationEvidence",
    "ReconciliationEvidenceKind",
    "ReconciliationReport",
    "ReconciliationResult",
    "ReconciliationState",
    "IssueSeverity",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_sha256",
    "canonicalize",
    "freeze_json",
    "historical_mappings_from_parser_yaml",
    "merge_complete_pages",
    "normalize_json",
    "read_manifest_jsonl",
    "reconcile_manifest_files",
    "reconcile_manifests",
    "reconcile_record",
    "render_manifest_jsonl",
    "sha256_bytes",
    "sha256_hex",
    "thaw_json",
    "wordpress_page_meta",
]
